### ISSUE TITLE
请问用这个登录校园网后，还会不会掉线

### ISSUE THREAD

**Issue by lzyjojo** [z4yx/GoAuthing#15]
远程办公，但经常掉线，然后就连不上了

**Comment by z4yx** [comment]
掉线是校园网的策略，与登录工具无关。想要保持在线的话，需要有持续的网络流量。

**Comment by ZenithalHourlyRate** [comment]
这个工具可以做到准入认证`auth-thu auth`准出认证`auth-thu login`以及保持在线`auth-thu online`（通过不间断发送请求实现持续网络流量），但具体效果与目前的准入准出联动系统以及无流量超时掉线系统有很大关系，不能保证其一直在线。

您可以通过搭配这三个任务（定时认证，定时准出，持续发送ping包）来尽量保证在线。您可以参考 systemd timer 来书写相关服务。
