### ISSUE TITLE
为什么没有认证，外面的网络可以 ping 通我的  IP 呢？

### ISSUE THREAD

**Issue by masterAllen** [z4yx/GoAuthing#19]
请问为什么我没有认证的时候，用外面的网络 ping 我的地址是可以 ping 通的，但是我 ping 外面的地址是不能 ping 通的呢？

**Comment by ZenithalHourlyRate** [comment]
> 请问为什么我没有认证的时候，我 ping 外面的地址是不能 ping 通的呢？

这是校园网特性，可以参考 https://thu.services/file/RealNameAuthenticationFAQ20190614.pdf 中第30节所提到的预策略

> 请问为什么我没有认证的时候，用外面的网络 ping 我的地址是可以 ping 通的？

这也是校园网特性，不过似乎没有文档
