### ISSUE TITLE
Questions on contribution

### ISSUE THREAD

**Issue by BaksiLi** [z4yx/GoAuthing#23]
前辈们好！

我最近在 OpenWRT (mips) 上用 GoAuthing，由于 boot 仅支持 `/etc/init.d` 的 init script（[参考](https://openwrt.org/docs/techref/initscripts)），所以自己写了一份，用一阵子了。考虑到身边用路由器的朋友不少，是否有可以提交到 [GoAuthing/docs](https://github.com/z4yx/GoAuthing/tree/master/docs) 中？可以的话我就 PR 了。

**Comment by ZenithalHourlyRate** [comment]
可以，请 PR
