### ISSUE TITLE
How to run the prebuilt binary on macOS

### ISSUE THREAD

**Issue by nmrenyi** [z4yx/GoAuthing#25]
Device: MacBook Air M2
macOS version: 13.0 (22A380)

I downloaded the [prebuilt binary](https://github.com/z4yx/GoAuthing/releases/download/v2.2/auth-thu.macos.arm64) for macOS arm64. Running `./auth-thu.macos.arm64` from terminal leads to the warning in this picture.
<img width="880" alt="Screenshot 2022-11-11 at 09 26 44" src="https://user-images.githubusercontent.com/46751328/201241115-8d39ac9c-9740-4b75-b9de-5c6b3f11868e.png">

Then I tried open it from Finder. Another warning shows up and still I cannot open it.
<img width="372" alt="Screenshot 2022-11-11 at 09 27 54" src="https://user-images.githubusercontent.com/46751328/201241396-dec35cff-7f3c-4c4c-a641-914415ef47f1.png">

So I wanna ask how I can run this on my MacBook. Thanks!

**Comment by jiegec** [comment]
1. Use `xattr -dr`
2. Right click & open in menu

**Comment by nmrenyi** [comment]
> * Use `xattr -dr`
> * Right click & open in menu

Thanks jiegec! I looked up the usage of `xattr -dr`. In the [examples](https://ss64.com/osx/xattr.html), I see that `xattr -d` removes the given attribute, for example `xattr -d com.apple.FinderInfo ~/MyApp`. 

But in my case, what attribute should I remove? I still do not understand how to use `xattr` here.

**Comment by nmrenyi** [comment]
Now problem solved. I ran `xattr -rd com.apple.quarantine auth-thu.macos.arm64` to remove the `com.apple.quarantine` attribute so that the prebuilt binary can be executed. I found this attribute by running `xattr -r auth-thu.macos.arm64`. Thanks :)
