### ISSUE TITLE
命令行认证报错

### ISSUE THREAD

**Issue by krzhck** [z4yx/GoAuthing#26]
❯ auth-thu
2022-11-25 03:05:36 ERROR auth-thu main.go:362 Auth error: Login Failed: Get "https://auth4.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=zhouyh18": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by z4yx** [comment]
看起来只是网络超时了，可能是偶然原因。如果在特定地点反复遇到该问题，请重新报告。

**Comment by TerenceXue-tech** [comment]
同样的问题

**Comment by WangYihang** [comment]
同样的问题

**Comment by TerenceXue-tech** [comment]
已解决，可以查一下默认路由，可能走了另一条有线网

**Comment by WangYihang** [comment]
位置：FIT 楼
这个链接我用 curl 是可以请求成功的，只不过时间比较久，而且是非常稳定的 16s（超过了代码里定义的任意一个 timeout），怀疑是 tauth4.tsinghua.edu.cn 内部的负载均衡可能有点问题。

```
root@OpenWrt:/etc# time curl "https://tauth4.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=[REDACTED]"
C_a_l_l_b_a_c_k({"challenge":"[REDACTED]","client_ip":"[REDACTED]","ecode":0,"error":"ok","error_msg":"","expire":"60","online_ip":"[REDACTED]","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20250403","st":1778207551})
real	0m 16.03s <---- 16s
user	0m 0.00s
sys	0m 0.00s

root@OpenWrt:/etc# time curl "https://tauth4.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=[REDACTED]"
C_a_l_l_b_a_c_k({"challenge":"[REDACTED]","client_ip":"[REDACTED]","ecode":0,"error":"ok","error_msg":"","expire":"41","online_ip":"[REDACTED]","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20250403","st":1778207570})
real	0m 16.04s <---- 16s
user	0m 0.01s
sys	0m 0.00s
```

<img width="2054" height="1463" alt="Image" src="https://github.com/user-attachments/assets/3a422fef-59ab-4b43-8af4-800ac6c0dc4c" />

可否给 goauthing 添加一个配置选项来增加 timeout？

**Comment by Starrah** [comment]
> 位置：FIT 楼 这个链接我用 curl 是可以请求成功的，只不过时间比较久，而且是非常稳定的 16s（超过了代码里定义的任意一个 timeout），怀疑是 tauth4.tsinghua.edu.cn 内部的负载均衡可能有点问题。
> 
> ```
> root@OpenWrt:/etc# time curl "https://tauth4.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=wyh-22"
> C_a_l_l_b_a_c_k({"challenge":"27e20b4acfb2722295441c4e37cd5679868cc4f869b7c753f54fb00630854eb9","client_ip":"101.6.42.94","ecode":0,"error":"ok","error_msg":"","expire":"60","online_ip":"101.6.42.94","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20250403","st":1778207551})
> real	0m 16.03s <---- 16s
> user	0m 0.00s
> sys	0m 0.00s
> 
> root@OpenWrt:/etc# time curl "https://tauth4.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=wyh-22"
> C_a_l_l_b_a_c_k({"challenge":"27e20b4acfb2722295441c4e37cd5679868cc4f869b7c753f54fb00630854eb9","client_ip":"101.6.42.94","ecode":0,"error":"ok","error_msg":"","expire":"41","online_ip":"101.6.42.94","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20250403","st":1778207570})
> real	0m 16.04s <---- 16s
> user	0m 0.01s
> sys	0m 0.00s
> ```
> 
> <img alt="Image" width="2000" height="1425" src="https://private-user-images.githubusercontent.com/16917636/589290244-3a422fef-59ab-4b43-8af4-800ac6c0dc4c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzgyMTEwMjMsIm5iZiI6MTc3ODIxMDcyMywicGF0aCI6Ii8xNjkxNzYzNi81ODkyOTAyNDQtM2E0MjJmZWYtNTlhYi00YjQzLThhZjQtODAwYWM2YzBkYzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNTA4VDAzMjUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYmM3MzhjMTNlZDg4MDkyNmRiMWEzMjI2MDliYTI4ZmNmODk3ZmEyOTk3ZmQ1OGU4NThkZWEzNTkwMDA2NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.AyR9q4D2_v_27Gtw5yrI9wGlKbrEnB-m-N-upBiOS9c">
> 可否给 goauthing 添加一个配置选项来增加 timeout？

@WangYihang 看到您测试使用的还是`tauth4.tsinghua.edu.cn`。这只是一个校园网升级过渡期间的临时域名，只用了几个月，现已停用，早已换回了正常的`auth4.tsinghua.edu.cn`。您是否可以使用`auth4.tsinghua.edu.cn`重测一次，看看是否还有问题。

**Comment by WangYihang** [comment]
哦？难道我用的 goauthing 的版本是旧的？

```
auth-thu version 2.3.5
```

应该是最新的 release 呀。

**Comment by Starrah** [comment]
早在2025.4.18的 be24095 中就已经切换回`auth`了。因此麻烦您改用auth做测试，不要用`tauth`了；并且请确保goauthing是最新版本。

**Comment by Starrah** [comment]
> 哦？难道我用的 goauthing 的版本是旧的？
> 
> ```
> auth-thu version 2.3.5
> ```
> 
> 应该是最新的 release 呀。

哦我知道了，没有发版导致的
我马上来发版

**Comment by Starrah** [comment]
@WangYihang 已发版，您再试试。

**Comment by WangYihang** [comment]
诶，好像换成 auth4 也是一样的问题。

在未认证状态下，响应时间一直是 16s 多一点。

```bash
root@OpenWrt:~# time curl "https://auth4.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=wyh-22" -vv
03:36:12.442281 [0-0] > GET /cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=wyh-22 HTTP/1.1
03:36:12.442281 [0-0] > Host: auth4.tsinghua.edu.cn
03:36:12.442281 [0-0] > User-Agent: curl/8.12.1
03:36:12.442281 [0-0] > Accept: */*
03:36:12.442281 [0-0] > 
03:36:12.445490 [0-0] < HTTP/1.1 200 OK
03:36:12.445739 [0-0] < Server: nginx
03:36:12.445767 [0-0] < Date: Fri, 08 May 2026 03:36:12 GMT
03:36:12.445785 [0-0] < Content-Type: application/json; charset=utf-8
03:36:12.445830 [0-0] < Content-Length: 276
03:36:12.445884 [0-0] < Connection: keep-alive
03:36:12.445899 [0-0] < Srun-Server: SRunCGIAuthIntfSvr V1.18 B20250403
03:36:12.445914 [0-0] < X-Frame-Options: SAMEORIGIN
03:36:12.445927 [0-0] < Set-Cookie: thuwebcookie-47873=ALAEAGGFFAAA; Path=/; HttpOnly
03:36:12.445942 [0-0] < 
C_a_l_l_b_a_c_k({"challenge":"241f27378b2baa1e07158d39703921a70a83362431de77b8f509c692fb47feb1","client_ip":"101.6.42.94","ecode":0,"error":"ok","error_msg":"","expire":"60","online_ip":"101.6.42.94","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20250403","st":1778211372})
real	0m 16.04s <---------------- 依然有 16s
user	0m 0.01s
sys	0m 0.00s

root@OpenWrt:~# time curl "https://auth4.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=wyh-22" -vv
03:36:54.875569 [0-0] > GET /cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=wyh-22 HTTP/1.1
03:36:54.875569 [0-0] > Host: auth4.tsinghua.edu.cn
03:36:54.875569 [0-0] > User-Agent: curl/8.12.1
03:36:54.875569 [0-0] > Accept: */*
03:36:54.875569 [0-0] > 
03:36:54.878371 [0-0] < HTTP/1.1 200 OK
03:36:54.878606 [0-0] < Server: nginx
03:36:54.878753 [0-0] < Date: Fri, 08 May 2026 03:36:54 GMT
03:36:54.878785 [0-0] < Content-Type: application/json; charset=utf-8
03:36:54.878842 [0-0] < Content-Length: 276
03:36:54.878859 [0-0] < Connection: keep-alive
03:36:54.878873 [0-0] < Srun-Server: SRunCGIAuthIntfSvr V1.18 B20250403
03:36:54.878887 [0-0] < X-Frame-Options: SAMEORIGIN
03:36:54.878900 [0-0] < Set-Cookie: thuwebcookie-47873=ALAEAGGFFAAA; Path=/; HttpOnly
03:36:54.878915 [0-0] < 
C_a_l_l_b_a_c_k({"challenge":"40eecbb202eccf96328005164593ad559400471b79e995e5d7d1be8bd64b8d7d","client_ip":"101.6.42.94","ecode":0,"error":"ok","error_msg":"","expire":"60","online_ip":"101.6.42.94","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20250403","st":1778211414})
real	0m 16.03s <---------------- 依然有 16s
user	0m 0.00s
sys	0m 0.00s
```

手动在 userreg.tsinghua.edu.cn 准入代认证之后，再访问响应时间就马上下来了。

```bash

root@OpenWrt:~# time curl "https://auth4.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=wyh-22" -vv
03:38:30.892269 [0-0] > GET /cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=wyh-22 HTTP/1.1
03:38:30.892269 [0-0] > Host: auth4.tsinghua.edu.cn
03:38:30.892269 [0-0] > User-Agent: curl/8.12.1
03:38:30.892269 [0-0] > Accept: */*
03:38:30.892269 [0-0] > 
03:38:30.894081 [0-0] < HTTP/1.1 200 OK
03:38:30.894289 [0-0] < Server: nginx
03:38:30.894307 [0-0] < Date: Fri, 08 May 2026 03:38:30 GMT
03:38:30.894321 [0-0] < Content-Type: application/json; charset=utf-8
03:38:30.894345 [0-0] < Content-Length: 276
03:38:30.894360 [0-0] < Connection: keep-alive
03:38:30.894373 [0-0] < Srun-Server: SRunCGIAuthIntfSvr V1.18 B20250403
03:38:30.894386 [0-0] < X-Frame-Options: SAMEORIGIN
03:38:30.894400 [0-0] < Set-Cookie: thuwebcookie-47873=ALAEAGGFFAAA; Path=/; HttpOnly
03:38:30.894414 [0-0] < 
C_a_l_l_b_a_c_k({"challenge":"11e45aa6fd097b3f85b32ec70b9f61e57530b11ca642a78a2b9675fe3207135c","client_ip":"101.6.42.94","ecode":0,"error":"ok","error_msg":"","expire":"60","online_ip":"101.6.42.94","res":"ok","srun_ver":"SRunCGIAuthIntfSvr V1.18 B20250403","st":1778211510})real	0m 0.03s
user	0m 0.01s <---------------- 认证之后马上恢复正常。
sys	0m 0.00s
```
