### ISSUE TITLE
Could not auth under ipv6 in OpenWrt

### ISSUE THREAD

**Issue by Bostoncake** [z4yx/GoAuthing#31]
I tried to use GoAuthing on my OpenWrt system using `./auth-thu -u <MY_USERNAME> -p <MY_PASSWORD> auth --ipv6` and got the following error:

> 2023-08-25 15:24:14 ERROR auth-thu main.go:362 Auth error: Login Failed: Get "https://auth6.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=<MY_USERNAME>": dial tcp: lookup auth6.tsinghua.edu.cn on 127.0.0.1:53: no such host

Directly authing ipv4 is OK in my environment. I wonder if there are any suggestions on how to successfully auth6? Thanks!

**Comment by Bostoncake** [comment]
I ran the command under debug mode and got the followings:

> 2023-08-25 15:31:24 DEBUG auth-thu main.go:93 Settings Username: "<MY_USERNAME>"
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:94 Settings Ip: ""
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:95 Settings Host: ""
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:96 Settings HookSucc: ""
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:97 Settings NoCheck: false
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:98 Settings V6: true
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:99 Settings KeepOn: false
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:100 Settings Insecure: false
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:101 Settings Daemon: false
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:102 Settings Debug: true
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:103 Settings AcID: ""
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:104 Settings Campus: false
> 2023-08-25 15:31:24 DEBUG libauth requests.go:223 GET "http://mirrors6.tuna.tsinghua.edu.cn/"
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:295 Failed to get ac_id: Get "http://mirrors6.tuna.tsinghua.edu.cn/": dial tcp: lookup mirrors6.tuna.tsinghua.edu.cn on 127.0.0.1:53: no such host
> 2023-08-25 15:31:24 DEBUG auth-thu main.go:296 Login may fail with 'IP地址异常'.
> 2023-08-25 15:31:24 DEBUG libauth requests.go:134 GET "https://auth6.tsinghua.edu.cn/srun_portal_pc.php?ac_id="
> 2023-08-25 15:31:24 DEBUG libauth requests.go:245 Getting challenge...
> 2023-08-25 15:31:24 DEBUG libauth requests.go:98 GET "https://auth6.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=<MY_USERNAME>"
> 2023-08-25 15:31:24 ERROR auth-thu main.go:362 Auth error: Login Failed: Get "https://auth6.tsinghua.edu.cn/cgi-bin/get_challenge?callback=C_a_l_l_b_a_c_k&double_stack=1&ip=&username=<MY_USERNAME>": dial tcp: lookup auth6.tsinghua.edu.cn on 127.0.0.1:53: no such host

**Comment by jiegec** [comment]
127.0.0.1:53 seems to be an address of DNS server, please check your DNS configuration.

**Comment by Bostoncake** [comment]
> 127.0.0.1:53 seems to be an address of DNS server, please check your DNS configuration.

I tried to fix my dns configurations but discovered a strange problem.
When I had my OpenClash service off, I could not ping ipv6 sites (byr.pt) nor could I open the site in my browser. However, when I had OpenClash on and choose to access ipv6 under proxy, I could ping byr.pt but still cannot open the site in my browser. When I had OpenClash on and choose not to access ipv6 under proxy, I could not ping byr.pt nor could I open the site in my browser.

**Comment by Bostoncake** [comment]
> > 127.0.0.1:53 seems to be an address of DNS server, please check your DNS configuration.
> 
> I tried to fix my dns configurations but discovered a strange problem. When I had my OpenClash service off, I could not ping ipv6 sites (byr.pt) nor could I open the site in my browser. However, when I had OpenClash on and choose to access ipv6 under proxy, I could ping byr.pt but still cannot open the site in my browser. When I had OpenClash on and choose not to access ipv6 under proxy, I could not ping byr.pt nor could I open the site in my browser.

And yes, I could only auth ipv6 when I had my OpenClash service on and access ipv6 under proxy.

**Comment by Bostoncake** [comment]
I guess it is not the problem of GoAuthing and I will go and check my OpwnWrt settings.
