### ISSUE TITLE
`login`命令报错

### ISSUE THREAD

**Issue by FranGuam** [z4yx/GoAuthing#41]
与 #32 问题相同，但在新版本中似乎未得到解决

版本：2.1.2 on OpenWRT 22.03

环境：紫荆1号楼 宿舍有线网

报错信息：

```bash
Sat Sep  7 11:46:45 2024 daemon.notice procd: /etc/rc.d/S99goauthing: 2024-09-07 03:46:45 ERROR auth-thu main.go:399 Login error: Get "http://net.tsinghua.edu.cn/do_login.php?ac_id=1&action=login&password=******&username=******": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

其他描述：使用`auth`命令可以正常连接，`login`似乎是无用的？

**Comment by FranGuam** [comment]
补充：该报错可以稳定复现

**Comment by jiegec** [comment]
有线网请用 auth.tsinghua.edu.cn 准入。

**Comment by jiegec** [comment]
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/c33589c2-c23f-4f2a-b46b-edfdae91a99c">

**Comment by FranGuam** [comment]
> 有线网请用 auth.tsinghua.edu.cn 准入。

意思是只需要`auth`不需要`login`？

**Comment by jiegec** [comment]
> > 有线网请用 auth.tsinghua.edu.cn 准入。
> 
> 意思是只需要`auth`不需要`login`？

yes
