### ISSUE TITLE
`auth -o` would deauthenticate all clients

### ISSUE THREAD

**Issue by ZenithalHourlyRate** [z4yx/GoAuthing#8]
Reproduced on v1.6.1, v.1.7, v1.9.2

Both `auth -o` and `auth -6 -o` suffer from this issue.

Several days ago when developing v1.7, this wasn't happening. It is suspected that usereg changed somehow in the meantime, which broke `auth -o`.

Also reported by @NickCao

**Comment by ashen0xa** [comment]
Cannot reproduce on current `master` branch bc84baad74076067d6f5f8b1ff679a8e1e996cd4 on `macOS 10.15.7`with `go 1.15.1 darwin/amd64`.

When issuing one of `deauth` or `deauth -6`, *both* v4 and v6 of the client will be logged out (unlike clicking `logout` on auth6 portal, which only affects v6). But other clients remain connected.

**Comment by ZenithalHourlyRate** [comment]
I tested for another time that with bc84baad74076067d6f5f8b1ff679a8e1e996cd4 both `auth -o` and `auth -o -6` would deauth all clients. However, with #9 both `auth -o` and `auth -6 -o` worked as intended.
